from graph import *

f_ob=circle(250,300,150)
changeFillColor(f_ob, "Yellow")
f_ob=circle(200,250,20)
changeFillColor(f_ob, "red")
f_ob=circle(300,250,20)
changeFillColor(f_ob, "red")
f_ob=circle(200,250,10)
changeFillColor(f_ob, "black")
f_ob=circle(300,250,10)
changeFillColor(f_ob, "black")

p1=[200,350]
p2=[200,370]
p3=[300,370]
p4=[300,350]
points=[p1,p2,p3,p4]
f_ob=polygon(points)
changeFillColor(f_ob, "black")

p1=[200,350]
p2=[200,370]
p3=[300,370]
p4=[300,350]
points=[p1,p2,p3,p4]
f_ob=polygon(points)
changeFillColor(f_ob, "black")

p1=[220,200]
p2=[210,220]
p3=[150,180]
p4=[160,160]
points=[p1,p2,p3,p4]
f_ob=polygon(points)
changeFillColor(f_ob, "black")

p1=[280,200]
p2=[290,220]
p3=[350,180]
p4=[340,160]
points=[p1,p2,p3,p4]
f_ob=polygon(points)
changeFillColor(f_ob, "black")
